D:/MLOps/dataset/
[2021-10-23 01:19:42,187][tensorflow][INFO] - Load image with size: 7553, num_label: 2, labels: with_mask, without_mask.
[2021-10-23 01:19:42,190][tensorflow][INFO] - Retraining the models...
[2021-10-23 01:19:42,192][absl][INFO] - Using C:\Users\phant\AppData\Local\Temp\tfhub_modules to cache modules.
C:\Users\phant\.virtualenvs\MLOps-he8T28m9\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
hub_keras_layer_v1v2 (HubKer (None, 1280)              2257984
_________________________________________________________________
dropout (Dropout)            (None, 1280)              0
_________________________________________________________________
dense (Dense)                (None, 2)                 2562
=================================================================
Total params: 2,260,546
Trainable params: 2,562
Non-trainable params: 2,257,984
_________________________________________________________________
None
Epoch 1/10









188/188 [==============================] - 27s 121ms/step - loss: 0.2807 - accuracy: 0.9712 - val_loss: 0.2389 - val_accuracy: 0.9918
Epoch 2/10








188/188 [==============================] - 22s 115ms/step - loss: 0.2390 - accuracy: 0.9902 - val_loss: 0.2336 - val_accuracy: 0.9918
Epoch 3/10








188/188 [==============================] - 21s 113ms/step - loss: 0.2333 - accuracy: 0.9920 - val_loss: 0.2272 - val_accuracy: 0.9959
Epoch 4/10








188/188 [==============================] - 21s 113ms/step - loss: 0.2297 - accuracy: 0.9947 - val_loss: 0.2257 - val_accuracy: 0.9959
Epoch 5/10








188/188 [==============================] - 21s 111ms/step - loss: 0.2273 - accuracy: 0.9952 - val_loss: 0.2254 - val_accuracy: 0.9959
Epoch 6/10








188/188 [==============================] - 21s 112ms/step - loss: 0.2270 - accuracy: 0.9963 - val_loss: 0.2259 - val_accuracy: 0.9932
Epoch 7/10








188/188 [==============================] - 21s 112ms/step - loss: 0.2261 - accuracy: 0.9957 - val_loss: 0.2284 - val_accuracy: 0.9932
Epoch 8/10








188/188 [==============================] - 21s 112ms/step - loss: 0.2264 - accuracy: 0.9963 - val_loss: 0.2289 - val_accuracy: 0.9932
Epoch 9/10








188/188 [==============================] - 24s 130ms/step - loss: 0.2255 - accuracy: 0.9958 - val_loss: 0.2252 - val_accuracy: 0.9946
Epoch 10/10









188/188 [==============================] - 21s 112ms/step - loss: 0.2230 - accuracy: 0.9965 - val_loss: 0.2240 - val_accuracy: 0.9959

24/24 [==============================] - 6s 97ms/step - loss: 0.2198 - accuracy: 0.9974
0.2198256403207779
0.9973545074462891
Error executing job with overrides: []
Traceback (most recent call last):
  File "D:\MLOps\FMClassifier\train.py", line 49, in main
    wandb.log({"loss": loss},{"accuracy": accuracy})
  File "C:\Users\phant\.virtualenvs\MLOps-he8T28m9\lib\site-packages\wandb\sdk\wandb_run.py", line 1213, in log
    if self.history._step > step:
TypeError: '>' not supported between instances of 'int' and 'dict'
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.